pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Yandex Mobile Ads SDK
        maven { url = uri("https://maven.yandex.ru/yandex-mobile-ads/") }
    }
}
rootProject.name = "RoboRacer"
include ':app'
